import { createContext, useContext, useState } from 'react';
import type { ReactNode } from 'react';

export type Language = 'es' | 'en';

const LanguageContext = createContext<{
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
} | null>(null);

const translations: Record<Language, Record<string, string>> = {
  es: {
    // Header
    'header.search': 'Buscar en Business Hub...',
    'header.notifications': 'Notificaciones',
    'header.noNotifications': 'Sin notificaciones nuevas.',
    'header.markAllAsRead': 'Marcar todas como leídas',
    'header.language': 'Idioma',
    'header.darkMode': 'Modo oscuro',
    'header.lightMode': 'Modo claro',
    'header.accountSettings': 'Configuración de cuenta',
    'header.logout': 'Cerrar Sesión',

    // Sidebar
    'sidebar.dashboard': 'Dashboard',
    'sidebar.activos': 'Activos',
    'sidebar.oportunidades': 'Oportunidades',
    'sidebar.acuerdos': 'Acuerdos',
    'sidebar.compromisos': 'Compromisos',
    'sidebar.evidencias': 'Evidencias',
    'sidebar.reportes': 'Reportes',
    'sidebar.parametrizacion': 'Parametrización',
    'sidebar.reportesAdmin': 'Reportes Admin',
    'sidebar.audiencias': 'Audiencias',
    'sidebar.marcas': 'Marcas',
    'sidebar.marketplace': 'Marketplace',
    'sidebar.contraer': 'Contraer',

    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.description': 'Visión ejecutiva de la operación',
    'dashboard.metrics': 'Indicadores clave',
    'dashboard.noData': 'Sin datos',
    'dashboard.recentActivity': 'Actividad reciente',
    'dashboard.pipelineValue': 'Valor del pipeline',
    'dashboard.activeAgreements': 'Acuerdos activos',
    'dashboard.pendingCommitments': 'Compromisos pendientes',

    // Activos
    'activos.title': 'Activos',
    'activos.description': 'Gestión de activos comerciales',
    'activos.new': 'Nuevo activo',
    'activos.edit': 'Editar',
    'activos.delete': 'Eliminar',
    'activos.view': 'Ver detalle',
    'activos.noResults': 'No hay activos que coincidan',
    'activos.category': 'Categoría',
    'activos.channel': 'Canal',
    'activos.value': 'Valoración',
    'activos.inventory': 'Inventario',
    'activos.status': 'Estado',

    // Oportunidades
    'oportunidades.title': 'Oportunidades',
    'oportunidades.description': 'Pipeline comercial',
    'oportunidades.new': 'Nueva oportunidad',
    'oportunidades.edit': 'Editar',
    'oportunidades.delete': 'Eliminar',
    'oportunidades.view': 'Ver detalle',
    'oportunidades.noResults': 'No hay oportunidades que coincidan',
    'oportunidades.brand': 'Marca',
    'oportunidades.stage': 'Etapa',
    'oportunidades.probability': 'Probabilidad',
    'oportunidades.estimatedValue': 'Valor estimado',
    'oportunidades.closureDate': 'Fecha cierre estimada',

    // Acuerdos
    'acuerdos.title': 'Acuerdos',
    'acuerdos.description': 'Patrocinios cerrados',
    'acuerdos.new': 'Nuevo acuerdo',
    'acuerdos.edit': 'Editar',
    'acuerdos.delete': 'Eliminar',
    'acuerdos.view': 'Ver detalle',
    'acuerdos.noResults': 'No hay acuerdos que coincidan',
    'acuerdos.sponsor': 'Patrocinador',
    'acuerdos.value': 'Valor',
    'acuerdos.startDate': 'Fecha inicio',
    'acuerdos.endDate': 'Fecha fin',
    'acuerdos.completion': 'Cumplimiento',

    // Compromisos
    'compromisos.title': 'Compromisos',
    'compromisos.description': 'Gestión de entregas',
    'compromisos.new': 'Nuevo compromiso',
    'compromisos.edit': 'Editar',
    'compromisos.delete': 'Eliminar',
    'compromisos.view': 'Ver detalle',
    'compromisos.noResults': 'No hay compromisos que coincidan',
    'compromisos.deliverable': 'Entregable',
    'compromisos.dueDate': 'Fecha límite',
    'compromisos.priority': 'Prioridad',
    'compromisos.responsible': 'Responsable',
    'compromisos.status': 'Estado',

    // Evidencias
    'evidencias.title': 'Evidencias',
    'evidencias.description': 'Pruebas de cumplimiento',
    'evidencias.new': 'Nueva evidencia',
    'evidencias.edit': 'Editar',
    'evidencias.delete': 'Eliminar',
    'evidencias.view': 'Ver detalle',
    'evidencias.noResults': 'No hay evidencias que coincidan',
    'evidencias.type': 'Tipo',
    'evidencias.title_label': 'Título',
    'evidencias.date': 'Fecha ejecución',
    'evidencias.status': 'Estado',

    // Reportes
    'reportes.title': 'Reportes',
    'reportes.description': 'Informes ejecutivos',
    'reportes.noResults': 'No hay reportes que coincidan',
    'reportes.export': 'Exportar (demostración)',
    'reportes.fulfillment': 'Cumplimiento',
    'reportes.mediaValue': 'Valor mediático',
    'reportes.reach': 'Alcance',
    'reportes.interactions': 'Interacciones',

    // Parametrización
    'parametrizacion.title': 'Parametrización',
    'parametrizacion.description': 'Configuración del sistema',
    'parametrizacion.sectors': 'Sectores',
    'parametrizacion.users': 'Usuarios',
    'parametrizacion.companies': 'Compañías',
    'parametrizacion.subscriptions': 'Suscripciones',
    'parametrizacion.back': 'Volver a Parametrización',
    'parametrizacion.new': 'Nuevo',
    'parametrizacion.edit': 'Editar',
    'parametrizacion.delete': 'Eliminar',
    'parametrizacion.name': 'Nombre',
    'parametrizacion.fieldDescription': 'Descripción',

    // Audiencias
    'audiencias.title': 'Audiencias',
    'audiencias.description': 'Gestión de segmentos y canales',
    'audiencias.segments': 'Segmentos',
    'audiencias.channels': 'Canales',
    'audiencias.campaigns': 'Campañas',
    'audiencias.capabilities': 'Capacidades',

    // Marcas
    'marcas.title': 'Marcas',
    'marcas.description': 'Directorio de marcas y patrocinadores potenciales.',
    'marcas.new': 'Nueva marca',
    'marcas.edit': 'Editar',
    'marcas.delete': 'Eliminar',
    'marcas.view': 'Ver detalle',
    'marcas.noResults': 'No hay marcas que coincidan',

    // Common buttons and messages
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.close': 'Cerrar',
    'common.edit': 'Editar',
    'common.delete': 'Eliminar',
    'common.back': 'Atrás',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.warning': 'Advertencia',
    'common.info': 'Información',
    'common.create': 'Crear',
    'common.update': 'Actualizar',
    'common.remove': 'Eliminar',
    'common.refresh': 'Actualizar',
    'common.export': 'Exportar',
    'common.import': 'Importar',
    'common.noResults': 'No hay resultados',
    'common.emptyState': 'Sin datos para mostrar',

    // Forms
    'form.email': 'Correo electrónico',
    'form.username': 'Usuario',
    'form.password': 'Contraseña',
    'form.confirmPassword': 'Confirmar contraseña',
    'form.name': 'Nombre',
    'form.description': 'Descripción',
    'form.required': 'Campo requerido',
    'form.invalidEmail': 'Correo electrónico inválido',
    'form.passwordMinLength': 'La contraseña debe tener al menos 8 caracteres',

    // States and Status
    'status.active': 'Activo',
    'status.inactive': 'Inactivo',
    'status.pending': 'Pendiente',
    'status.completed': 'Cumplido',
    'status.cancelled': 'Cancelado',
    'status.paused': 'Pausado',
    'status.inProgress': 'En curso',
    'status.inReview': 'En revisión',
    'status.approved': 'Aprobado',
    'status.rejected': 'Rechazado',

    // Date and Time
    'time.today': 'Hoy',
    'time.yesterday': 'Ayer',
    'time.thisWeek': 'Esta semana',
    'time.thisMonth': 'Este mes',
    'time.thisYear': 'Este año',

    // Login Page
    'login.secureAccess': 'Acceso seguro',
    'login.title': 'Inicia sesión',
    'login.subtitle': 'Ingresa con el correo o usuario de tu cuenta.',
    'login.emailLabel': 'Correo o usuario',
    'login.emailPlaceholder': 'usuario o correo@empresa.com',
    'login.passwordLabel': 'Contraseña',
    'login.passwordPlaceholder': 'Ingresa tu contraseña',
    'login.forgotPassword': '¿Olvidaste tu contraseña?',
    'login.submitButton': 'Entrar al Business Hub',
    'login.validating': 'Validando...',
    'login.noAccount': '¿Aún no tienes cuenta?',
    'login.createAccount': 'Crear cuenta',
    'login.demoAccess': 'Acceso de demostración local',
    'login.platformDescription': 'Plataforma de gestión de patrocinios deportivos',
    'login.businessHub': 'Business Hub',
    'login.mainHeading': 'Convierte cada compromiso en valor demostrable.',
    'login.mainDescription': 'Una vista conectada de activos, oportunidades, acuerdos y resultados para gestionar el patrocinio deportivo con precisión.',
    'login.operationLabel': 'de la operación comercial',
    'login.liveLabel': 'de cumplimiento y evidencias',

    // Password Reset
    'passwordReset.title': 'Recuperar contraseña',
    'passwordReset.description': 'Ingresa tu correo electrónico o usuario para recibir un código de recuperación válido por 30 minutos.',
    'passwordReset.emailLabel': 'Correo o usuario',
    'passwordReset.emailPlaceholder': 'usuario@ejemplo.com o tu_usuario',
    'passwordReset.getCode': 'Obtener código',
    'passwordReset.sending': 'Enviando...',
    'passwordReset.cancel': 'Cancelar',
    'passwordReset.codeReceived': 'Código recibido:',
    'passwordReset.newPasswordLabel': 'Nueva contraseña',
    'passwordReset.newPasswordPlaceholder': 'Mínimo 8 caracteres',
    'passwordReset.confirmPasswordLabel': 'Confirmar contraseña',
    'passwordReset.confirmPasswordPlaceholder': 'Repite tu nueva contraseña',
    'passwordReset.resetButton': 'Restablecer contraseña',
    'passwordReset.resetting': 'Restableciendo...',
    'passwordReset.back': 'Atrás',
    'passwordReset.successTitle': 'Contraseña actualizada',
    'passwordReset.successMessage': 'Tu contraseña ha sido restablecida correctamente. Serás redirigido al login en breve.',
    'passwordReset.successMessage2': 'Código de recuperación generado. Úsalo en los próximos 30 minutos.',

    // Account Settings
    'accountSettings.title': 'Configuración de cuenta',
    'accountSettings.accountInfo': 'Información de la cuenta',
    'accountSettings.username': 'Usuario',
    'accountSettings.email': 'Correo electrónico',
    'accountSettings.subscriptionType': 'Tipo de suscripción',
    'accountSettings.changePassword': 'Cambiar contraseña',
    'accountSettings.currentPassword': 'Contraseña actual',
    'accountSettings.newPassword': 'Nueva contraseña',
    'accountSettings.confirmPassword': 'Confirmar nueva contraseña',
    'accountSettings.passwordUpdated': 'Contraseña actualizada',
    'accountSettings.passwordChanged': 'Tu contraseña ha sido cambiada correctamente.',

    // Date fields for users admin
    'users.validFrom': 'Válido desde',
    'users.validUntil': 'Válido hasta',
    'users.createdAt': 'Creado en',
    'users.updatedAt': 'Actualizado en',
    'users.lastLoginAt': 'Último acceso en',

    // Form Fields - Activos
    'activo.nombreDelActivo': 'Nombre del activo',
    'activo.categoria': 'Categoría',
    'activo.canalUbicacion': 'Canal o ubicación',
    'activo.descripcion': 'Descripción',
    'activo.valoracionCOP': 'Valoración (COP)',
    'activo.inventarioTotal': 'Inventario total',
    'activo.inventarioDisponible': 'Inventario disponible',
    'activo.alcanceEstimado': 'Alcance estimado',
    'activo.estado': 'Estado',
    'activo.derechosIncluidos': 'Derechos incluidos',
    'activo.audienciaCapacidad': 'Audiencia y capacidad de activación',
    'activo.segmentosRelacionados': 'Segmentos relacionados',
    'activo.canalActivacion': 'Canal de activación',
    'activo.tipoAudiencia': 'Tipo de audiencia',
    'activo.capacidadSegmentacion': 'Capacidad de segmentación',
    'activo.indicadoresDisponibles': 'Indicadores disponibles',
    'activo.frecuenciaMaxima': 'Frecuencia máxima',
    'activo.requiereSportsActGO': 'Requiere Sports Act GO',
    'activo.restricciones': 'Restricciones',

    // Form Fields - Oportunidades
    'oportunidad.marca': 'Marca',
    'oportunidad.responsable': 'Responsable',
    'oportunidad.etapa': 'Etapa',
    'oportunidad.valorEstimadoCOP': 'Valor estimado (COP)',
    'oportunidad.probabilidad': 'Probabilidad (%)',
    'oportunidad.fechaCierre': 'Fecha estimada de cierre',
    'oportunidad.activosPropuestos': 'Activos propuestos',
    'oportunidad.proximoPaso': 'Próximo paso',

    // Form Fields - Evidencias
    'evidencia.compromisoRelacionado': 'Compromiso relacionado',
    'evidencia.tipoEvidencia': 'Tipo de evidencia',
    'evidencia.fechaEjecucion': 'Fecha de ejecución',
    'evidencia.titulo': 'Título',
    'evidencia.descripcion': 'Descripción',
    'evidencia.ubicacionCanal': 'Ubicación o canal',
    'evidencia.enlace': 'Enlace (opcional)',

    // Form Fields - Compañías
    'compania.nombre': 'Nombre',
    'compania.sector': 'Sector',
    'compania.nombreContacto': 'Nombre del contacto',
    'compania.telefonoContacto': 'Teléfono contacto',
    'compania.telefono2Contacto': 'Teléfono 2 contacto',
    'compania.correoContacto': 'Correo contacto',
    'compania.correo2Contacto': 'Correo 2 contacto',
    'compania.logo': 'Logo (URL o ruta)',

    // Form Fields - Usuarios
    'usuario.correo': 'Correo',
    'usuario.usuario': 'Usuario',
    'usuario.contraseña': 'Contraseña',
    'usuario.nuevaContraseña': 'Nueva contraseña (opcional)',
    'usuario.suscripcion': 'Suscripción',
    'usuario.compania': 'Compañía',

    // Button Actions
    'button.cancelar': 'Cancelar',
    'button.guardarCambios': 'Guardar cambios',
    'button.crearActivo': 'Crear activo',
    'button.crearOportunidad': 'Crear oportunidad',
    'button.registrarEvidencia': 'Registrar evidencia',
    'button.crearCompania': 'Crear compañía',
    'button.crearSector': 'Crear sector',
    'button.crearUsuario': 'Crear usuario',
    'button.nuevoPlan': 'Nuevo plan',
    'button.guardarPlan': 'Guardar plan',
    'button.eliminarPlan': 'Eliminar plan',
    'button.cambiarContraseña': 'Cambiar contraseña',
    'button.atras': 'Atrás',
    'button.cambiando': 'Cambiando...',
    'button.guardando': 'Guardando...',
    'button.enviando': 'Enviando...',
    'button.nuevo': 'Nuevo',
    'button.editar': 'Editar',
    'button.eliminar': 'Eliminar',
    'button.cerrar': 'Cerrar',

    // Page Headers & Descriptions
    'dashboard.operacion': 'Visión ejecutiva de la operación comercial y de cumplimiento de patrocinios.',
    'activos.catalogo': 'Catálogo de activos comerciales disponibles para patrocinio.',
    'acuerdos.patrocinios': 'Patrocinios cerrados, vigencia y estado de cumplimiento.',
    'compromisos.entregas': 'Gestión operativa de los entregables prometidos a cada patrocinador.',
    'evidencias.repositorio': 'Repositorio de pruebas de cumplimiento de cada compromiso.',
    'oportunidades.pipeline': 'Pipeline comercial de negociaciones con marcas patrocinadoras.',
    'audiencias.header': 'Audiencias y alcance',
    'audiencias.descripcion': 'Gestión de segmentos, canales y campañas de alcance',
    'audiencias.demoDatos': 'Datos de demostración',
    'compania.header': 'Compañías',
    'compania.descripcion': 'Registra, modifica y elimina compañías patrocinadoras.',
    'sector.header': 'Sectores',
    'sector.descripcion': 'Configura el catálogo utilizado para clasificar compañías.',
    'usuario.header': 'Gestión de usuarios',
    'usuario.descripcion': 'Crea, modifica y elimina usuarios, suscripciones y compañías asignadas.',
    'suscripcion.header': 'Suscripciones',
    'suscripcion.descripcion': 'Configura los planes, precios, límites y características disponibles.',
    'reporte.header': 'Reportes',
    'reporte.descripcion': 'Informes ejecutivos de resultados para cada patrocinador.',

    // Dashboard
    'dashboard.accesosRapidos': 'Accesos rápidos',

    // Dashboard Stats
    'dashboard.valorPipeline': 'Valor del pipeline',
    'dashboard.oportunidadesAbiertas': 'Oportunidades abiertas',
    'dashboard.ingresosCerrados': 'Ingresos cerrados',
    'dashboard.acuerdosActivos': 'Acuerdos activos, próximos a vencer y finalizados',
    'dashboard.activosDisponibles': 'Activos disponibles',
    'dashboard.listosNegociar': 'Listos para negociar',
    'dashboard.incluyeProximosVencer': 'Incluye próximos a vencer',
    'dashboard.cumplimientoGeneral': 'Cumplimiento general',
    'dashboard.compromisoCumplidos': 'Compromisos cumplidos del total',
    'dashboard.compromisosVencidos': 'Compromisos vencidos',
    'dashboard.requierenAtencion': 'Requieren atención inmediata',
    'dashboard.totalActivos': 'Total de activos',
    'dashboard.disponibles': 'Disponibles',
    'dashboard.comprometidos': 'Comprometidos',
    'dashboard.valorVigente': 'Valor vigente',
    'dashboard.acuerdosTotales': 'Acuerdos totales',
    'dashboard.proximosVencer': 'Próximos a vencer',
    'dashboard.totalCompromisos': 'Total de compromisos',
    'dashboard.pendientesEnCurso': 'Pendientes y en curso',
    'dashboard.vencidos': 'Vencidos',
    'dashboard.cumplidos': 'Cumplidos',
    'dashboard.totalEvidencias': 'Total de evidencias',
    'dashboard.aprobadas': 'Aprobadas',
    'dashboard.enRevision': 'En revisión',
    'dashboard.rechazadas': 'Rechazadas',
    'dashboard.oportunidadesAbiertas2': 'Oportunidades abiertas',
    'dashboard.valorPipeline2': 'Valor en pipeline',
    'dashboard.ganadas': 'Firmadas',

    // Filter Labels
    'filter.todosLosEstados': 'Todos los estados',
    'filter.todasLasPrioridades': 'Todas las prioridades',
    'filter.todosLosResponsables': 'Todos los responsables',
    'filter.todasLasCategorias': 'Todas las categorías',
    'filter.todosLosAcuerdos': 'Todos los acuerdos',
    'filter.todoLosTipos': 'Todos los tipos',
    'filter.todosLosSegmentos': 'Todos los segmentos',
    'filter.quitar': 'Quitar filtro',

    // Search Placeholders
    'search.entregable': 'Buscar entregable...',
    'search.nombreCanal': 'Buscar por nombre o canal...',
    'search.acuerdoMarca': 'Buscar por acuerdo o marca...',
    'search.evidencia': 'Buscar evidencia...',
    'search.marca': 'Buscar por marca...',
    'search.campana': 'Buscar campaña...',
    'search.marcaAcuerdo': 'Buscar por marca o acuerdo...',

    // Status Labels
    'status.borrador': 'Borrador',
    'status.proximoVencer': 'Próximo a vencer',
    'status.finalizado': 'Finalizado',
    'status.enCurso2': 'En curso',
    'status.enRevision2': 'En revisión',
    'status.aprobada': 'Aprobada',
    'status.rechazada': 'Rechazada',
    'status.ganada': 'Firmada',
    'status.perdida': 'Perdida',
    'status.activa': 'Activa',
    'status.finalizada': 'Finalizada',

    // Table Headers
    'table.entregable': 'Entregable',
    'table.marca': 'Marca',
    'table.responsable': 'Responsable',
    'table.fechaLimite': 'Fecha límite',
    'table.prioridad': 'Prioridad',
    'table.progreso': 'Progreso',
    'table.estado': 'Estado',
    'table.activo': 'Activo',
    'table.categoria': 'Categoría',
    'table.valoracion': 'Valoración',
    'table.inventario': 'Inventario',
    'table.acuerdo': 'Acuerdo',
    'table.valor': 'Valor',
    'table.vigencia': 'Vigencia',
    'table.cumplimiento': 'Cumplimiento',
    'table.etapa': 'Etapa',
    'table.estimado': 'Valor estimado',
    'table.probabilidad': 'Probabilidad',
    'table.cierreEstimado': 'Cierre estimado',
    'table.campana': 'Campaña',
    'table.patrocinador': 'Patrocinador',
    'table.canal': 'Canal',
    'table.periodo': 'Periodo',
    'table.alcance': 'Alcance',
    'table.interacciones': 'Interacciones',
    'table.conversiones': 'Conversiones',
    'table.tasaConv': 'Tasa conv.',
    'table.acciones': 'Acciones',

    // Empty States
    'empty.noCompromisos': 'No hay compromisos que coincidan',
    'empty.ajustaFiltros': 'Ajusta la búsqueda o los filtros aplicados.',
    'empty.noActivos': 'No se encontraron activos',
    'empty.ajustaActivos': 'Ajusta los filtros de búsqueda o crea un nuevo activo comercial.',
    'empty.noAcuerdos': 'No hay acuerdos que coincidan',
    'empty.noEvidencias': 'No hay evidencias que coincidan',
    'empty.ajustaEvidencias': 'Ajusta los filtros o registra una nueva evidencia de cumplimiento.',
    'empty.noOportunidades': 'No hay oportunidades que coincidan',
    'empty.ajustaOportunidades': 'Ajusta los filtros o crea una nueva oportunidad comercial.',
    'empty.noCampanas': 'No hay campañas que coincidan',
    'empty.ajustaCampanas': 'Ajusta los filtros para ver otras campañas de audiencia.',
    'empty.noReportes': 'No hay reportes que coincidan',
    'empty.ajustaReportes': 'Ajusta la búsqueda para encontrar el reporte de un patrocinador.',
    'empty.reporteNoEncontrado': 'Reporte no encontrado',
    'empty.reporteNoGenerado': 'Aún no existe un reporte ejecutivo generado para este acuerdo.',
    'empty.acuerdoNoEncontrado': 'Acuerdo no encontrado',
    'empty.acuerdoEliminado': 'Es posible que haya sido eliminado o el enlace sea incorrecto.',
    'empty.sinEvidencias': 'Aún no hay evidencias registradas para este acuerdo.',
    'empty.sinOportunidades': 'Sin oportunidades en esta etapa',
    'empty.sinActivosAsociados': 'Este acuerdo no tiene activos asociados.',
    'empty.sinCompromisos': 'Este acuerdo aún no tiene compromisos definidos.',
    'empty.sinActivosVinculados': 'Sin activos comerciales vinculados todavía.',
    'empty.sinCompanias': 'Aún no hay compañías registradas.',
    'empty.sinDescripcion': 'Sin descripción',

    // Confirmation & Messages
    'confirm.eliminarCompania': '¿Eliminar la compañía {nombre}?',
    'confirm.eliminarSector': '¿Eliminar el sector {nombre}?',
    'confirm.eliminarSuscripcion': '¿Eliminar la suscripción {name}?',
    'confirm.eliminarUsuario': '¿Eliminar el usuario {username}?',

    // Success Messages
    'message.compañiaActualizada': 'Compañía actualizada correctamente.',
    'message.compañiaCreada': 'Compañía creada correctamente.',
    'message.compañiaEliminada': 'Compañía eliminada correctamente.',
    'message.sectorActualizado': 'Sector actualizado correctamente.',
    'message.sectorCreado': 'Sector creado correctamente.',
    'message.sectorEliminado': 'Sector eliminado correctamente.',
    'message.usuarioActualizado': 'Usuario actualizado correctamente.',
    'message.usuarioCreado': 'Usuario creado correctamente.',
    'message.usuarioEliminado': 'Usuario eliminado correctamente.',
    'message.planGuardado': 'Plan guardado correctamente.',
    'message.planEliminado': 'Plan eliminado correctamente.',
    'message.activoCreado': 'Activo creado correctamente.',
    'message.oportunidadMovida': 'Oportunidad movida a "{etapa}".',
    'message.oportunidadCreada': 'Oportunidad creada en el pipeline.',
    'message.evidenciaRegistrada': 'Evidencia registrada y enviada a revisión.',
    'message.evidenciaAprobada': 'Evidencia aprobada.',
    'message.evidenciaRechazada': 'Evidencia rechazada.',
    'message.compromisoActualizado': 'Compromiso actualizado a "{nuevoEstado}".',
    'message.renovacionRegistrada': 'Seguimiento de renovación registrado para este acuerdo.',
    'message.segmentoActualizado': 'Información agregada del segmento actualizada.',
    'message.activoYaVinculado': 'Ese activo ya está vinculado a este segmento.',
    'message.datosActualizados': 'Datos actualizados (simulación). No hay conexión real con Sports Act GO todavía.',
    'message.exportDemoAvailable': 'La exportación a PDF estará disponible al conectar el backend. Esta es una vista de demostración.',

    // Error Messages
    'error.noGuardarCompania': 'No fue posible guardar la compañía.',
    'error.noEliminarCompania': 'No fue posible eliminar la compañía.',
    'error.noCargarCompanias': 'No fue posible cargar las compañías.',
    'error.noCargarSectores': 'No fue posible cargar los sectores.',
    'error.noGuardarSector': 'No fue posible guardar el sector.',
    'error.noEliminarSector': 'No fue posible eliminar el sector.',
    'error.noCrearSector': 'No fue posible crear el sector.',
    'error.noCargarUsuarios': 'No fue posible cargar los usuarios.',
    'error.noGuardarUsuario': 'No fue posible guardar el usuario.',
    'error.noEliminarUsuario': 'No fue posible eliminar el usuario.',
    'error.noEliminarPropio': 'No puedes eliminar el usuario con el que estás conectado.',
    'error.noCargarPlanes': 'No fue posible cargar los planes.',
    'error.noGuardarPlan': 'No fue posible guardar el plan.',
    'error.noEliminarPlan': 'No fue posible eliminar el plan. Verifica que no tenga usuarios o accesos asociados.',
    'error.contrasenaNoCoincide': 'Las contraseñas no coinciden.',
    'error.contrasenaPocaLongitud': 'La contraseña debe tener al menos 8 caracteres.',
    'error.noCambiarContraseña': 'No fue posible cambiar la contraseña.',
    'error.noCrearCuenta': 'No fue posible crear la cuenta.',
    'error.noIniciarSesion': 'No fue posible iniciar sesión.',

    // Detail Cards
    'detail.resumenAcuerdo': 'Resumen del acuerdo',
    'detail.valorAcuerdo': 'Valor del acuerdo',
    'detail.vigencia': 'Vigencia',
    'detail.activosIncluidos': 'Activos incluidos',
    'detail.compromisosRelacionados': 'Compromisos relacionados',
    'detail.verTodos': 'Ver todos',
    'detail.patrocinador': 'Patrocinador',
    'detail.responsableInterno': 'Responsable interno',
    'detail.renovacion': 'Renovación',
    'detail.interes': 'Interés',
    'detail.iniciarSeguimiento': 'Iniciar seguimiento de renovación',
    'detail.seguimientoEnCurso': 'Seguimiento de renovación en curso.',
    'detail.vence': 'Vence',
    'detail.cumplimientoLabel': 'Cumplimiento',
    'detail.alcanceLabel': 'Alcance',
    'detail.interaccionesLabel': 'Interacciones',
    'detail.valorMediatico': 'Valor mediático',
    'detail.alcanceImpresiones': 'Alcance e impresiones mensuales',
    'detail.evolucionMetricas': 'Evolución de métricas de exposición',
    'detail.compromisosTitle': 'Compromisos',
    'detail.cumplidos': 'Cumplidos',
    'detail.pendientesEnCurso': 'Pendientes / en curso',
    'detail.galeriaEvidencias': 'Galería de evidencias',

    // Quick Actions
    'action.gestionarActivos': 'Gestionar activos',
    'action.verDisponibilidad': 'Ver disponibilidad e inventario',
    'action.verPipeline': 'Ver pipeline',
    'action.seguimientoNegociaciones': 'Seguimiento de negociaciones',
    'action.registrarEvidencia': 'Registrar evidencia',
    'action.subirPrueba': 'Subir prueba de cumplimiento',
    'action.verReportes': 'Ver reportes',
    'action.resultadoPatrocinador': 'Resultados por patrocinador',

    // Misc
    'misc.contatoInformacion': 'Información de contacto',
    'misc.detalleTransaccional': 'Detalle transaccional',
    'misc.auditoriaAntecedentes': 'Auditoría y antecedentes',
    'misc.periodoDatos': 'Datos de demostración',
    'misc.tabsAudiencias': 'Pestañas de audiencias',
    'misc.resumen': 'Resumen',
    'misc.segmentos': 'Segmentos',
    'misc.canales': 'Canales',
    'misc.campanasResultados': 'Campañas y resultados',
    'misc.filtrandoCampanas': 'Filtrando campañas relacionadas con el segmento {nombre}',
    'misc.planesDisponibles': 'Planes disponibles',
    'misc.seleccionaPlan': 'Selecciona un plan para editarlo, eliminarlo o crea uno nuevo.',
    'misc.seleccionadas': '{features.length} seleccionadas',
    'misc.companiasRegistradas': 'Compañías registradas',
    'misc.companiasDisponibles': '{companias.length} compañías disponibles',
    'misc.usuariosRegistrados': 'Usuarios',
    'misc.usuariosDisponibles': '{users.length} usuarios registrados',
    'misc.sectoresDisponibles': 'Sectores disponibles',
    'misc.sectoresRegistrados': '{sectores.length} sectores registrados',
    'misc.codigoSuscripcion': 'Código',
    'misc.nombreSuscripcion': 'Nombre',
    'misc.precioCOP': 'Precio COP',
    'misc.maximoUsuarios': 'Máximo de usuarios',
    'misc.descripcionSuscripcion': 'Descripción',
    'misc.caracteristicas': 'Características',
    'misc.sinLimite': 'Sin límite',
    'misc.seleccionaCaracteristicas': 'Selecciona las características',
    'misc.verReporteEjecutivo': 'Ver reporte ejecutivo',
    'misc.volverReportes': 'Volver a Reportes',
    'misc.volverAcuerdos': 'Volver a Acuerdos',
    'misc.periodoInforme': 'Periodo del informe:',
  },
  en: {
    // Header
    'header.search': 'Search in Business Hub...',
    'header.notifications': 'Notifications',
    'header.noNotifications': 'No new notifications.',
    'header.markAllAsRead': 'Mark all as read',
    'header.language': 'Language',
    'header.darkMode': 'Dark mode',
    'header.lightMode': 'Light mode',
    'header.accountSettings': 'Account Settings',
    'header.logout': 'Logout',

    // Sidebar
    'sidebar.dashboard': 'Dashboard',
    'sidebar.activos': 'Assets',
    'sidebar.oportunidades': 'Opportunities',
    'sidebar.acuerdos': 'Agreements',
    'sidebar.compromisos': 'Commitments',
    'sidebar.evidencias': 'Evidence',
    'sidebar.reportes': 'Reports',
    'sidebar.parametrizacion': 'Configuration',
    'sidebar.reportesAdmin': 'Admin Reports',
    'sidebar.audiencias': 'Audiences',
    'sidebar.marcas': 'Brands',
    'sidebar.marketplace': 'Marketplace',
    'sidebar.contraer': 'Collapse',

    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.description': 'Executive overview of operations',
    'dashboard.metrics': 'Key indicators',
    'dashboard.noData': 'No data',
    'dashboard.recentActivity': 'Recent activity',
    'dashboard.pipelineValue': 'Pipeline value',
    'dashboard.activeAgreements': 'Active agreements',
    'dashboard.pendingCommitments': 'Pending commitments',

    // Activos
    'activos.title': 'Assets',
    'activos.description': 'Commercial assets management',
    'activos.new': 'New asset',
    'activos.edit': 'Edit',
    'activos.delete': 'Delete',
    'activos.view': 'View detail',
    'activos.noResults': 'No assets found',
    'activos.category': 'Category',
    'activos.channel': 'Channel',
    'activos.value': 'Value',
    'activos.inventory': 'Inventory',
    'activos.status': 'Status',

    // Oportunidades
    'oportunidades.title': 'Opportunities',
    'oportunidades.description': 'Sales pipeline',
    'oportunidades.new': 'New opportunity',
    'oportunidades.edit': 'Edit',
    'oportunidades.delete': 'Delete',
    'oportunidades.view': 'View detail',
    'oportunidades.noResults': 'No opportunities found',
    'oportunidades.brand': 'Brand',
    'oportunidades.stage': 'Stage',
    'oportunidades.probability': 'Probability',
    'oportunidades.estimatedValue': 'Estimated value',
    'oportunidades.closureDate': 'Estimated closure date',

    // Acuerdos
    'acuerdos.title': 'Agreements',
    'acuerdos.description': 'Closed sponsorships',
    'acuerdos.new': 'New agreement',
    'acuerdos.edit': 'Edit',
    'acuerdos.delete': 'Delete',
    'acuerdos.view': 'View detail',
    'acuerdos.noResults': 'No agreements found',
    'acuerdos.sponsor': 'Sponsor',
    'acuerdos.value': 'Value',
    'acuerdos.startDate': 'Start date',
    'acuerdos.endDate': 'End date',
    'acuerdos.completion': 'Completion',

    // Compromisos
    'compromisos.title': 'Commitments',
    'compromisos.description': 'Delivery management',
    'compromisos.new': 'New commitment',
    'compromisos.edit': 'Edit',
    'compromisos.delete': 'Delete',
    'compromisos.view': 'View detail',
    'compromisos.noResults': 'No commitments found',
    'compromisos.deliverable': 'Deliverable',
    'compromisos.dueDate': 'Due date',
    'compromisos.priority': 'Priority',
    'compromisos.responsible': 'Responsible',
    'compromisos.status': 'Status',

    // Evidencias
    'evidencias.title': 'Evidence',
    'evidencias.description': 'Compliance proof',
    'evidencias.new': 'New evidence',
    'evidencias.edit': 'Edit',
    'evidencias.delete': 'Delete',
    'evidencias.view': 'View detail',
    'evidencias.noResults': 'No evidence found',
    'evidencias.type': 'Type',
    'evidencias.title_label': 'Title',
    'evidencias.date': 'Execution date',
    'evidencias.status': 'Status',

    // Reportes
    'reportes.title': 'Reports',
    'reportes.description': 'Executive reports',
    'reportes.noResults': 'No reports found',
    'reportes.export': 'Export (demo)',
    'reportes.fulfillment': 'Fulfillment',
    'reportes.mediaValue': 'Media value',
    'reportes.reach': 'Reach',
    'reportes.interactions': 'Interactions',

    // Parametrización
    'parametrizacion.title': 'Configuration',
    'parametrizacion.description': 'System settings',
    'parametrizacion.sectors': 'Sectors',
    'parametrizacion.users': 'Users',
    'parametrizacion.companies': 'Companies',
    'parametrizacion.subscriptions': 'Subscriptions',
    'parametrizacion.back': 'Back to Configuration',
    'parametrizacion.new': 'New',
    'parametrizacion.edit': 'Edit',
    'parametrizacion.delete': 'Delete',
    'parametrizacion.name': 'Name',
    'parametrizacion.fieldDescription': 'Description',

    // Audiencias
    'audiencias.title': 'Audiences',
    'audiencias.description': 'Segment and channel management',
    'audiencias.segments': 'Segments',
    'audiencias.channels': 'Channels',
    'audiencias.campaigns': 'Campaigns',
    'audiencias.capabilities': 'Capabilities',

    // Marcas
    'marcas.title': 'Brands',
    'marcas.description': 'Directory of brands and potential sponsors.',
    'marcas.new': 'New brand',
    'marcas.edit': 'Edit',
    'marcas.delete': 'Delete',
    'marcas.view': 'View detail',
    'marcas.noResults': 'No brands found',

    // Common buttons and messages
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.back': 'Back',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.warning': 'Warning',
    'common.info': 'Information',
    'common.create': 'Create',
    'common.update': 'Update',
    'common.remove': 'Remove',
    'common.refresh': 'Refresh',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.noResults': 'No results',
    'common.emptyState': 'No data to display',

    // Forms
    'form.email': 'Email',
    'form.username': 'Username',
    'form.password': 'Password',
    'form.confirmPassword': 'Confirm password',
    'form.name': 'Name',
    'form.description': 'Description',
    'form.required': 'Required field',
    'form.invalidEmail': 'Invalid email address',
    'form.passwordMinLength': 'Password must be at least 8 characters',

    // States and Status
    'status.active': 'Active',
    'status.inactive': 'Inactive',
    'status.pending': 'Pending',
    'status.completed': 'Completed',
    'status.cancelled': 'Cancelled',
    'status.paused': 'Paused',
    'status.inProgress': 'In Progress',
    'status.inReview': 'In Review',
    'status.approved': 'Approved',
    'status.rejected': 'Rejected',

    // Date and Time
    'time.today': 'Today',
    'time.yesterday': 'Yesterday',
    'time.thisWeek': 'This week',
    'time.thisMonth': 'This month',
    'time.thisYear': 'This year',

    // Login Page
    'login.secureAccess': 'Secure access',
    'login.title': 'Sign in',
    'login.subtitle': 'Enter with your account email or username.',
    'login.emailLabel': 'Email or username',
    'login.emailPlaceholder': 'username or email@company.com',
    'login.passwordLabel': 'Password',
    'login.passwordPlaceholder': 'Enter your password',
    'login.forgotPassword': 'Forgot your password?',
    'login.submitButton': 'Enter Business Hub',
    'login.validating': 'Validating...',
    'login.noAccount': "Don't have an account yet?",
    'login.createAccount': 'Create account',
    'login.demoAccess': 'Local demo access',
    'login.platformDescription': 'Sports sponsorship management platform',
    'login.businessHub': 'Business Hub',
    'login.mainHeading': 'Turn every commitment into demonstrable value.',
    'login.mainDescription': 'A connected view of assets, opportunities, agreements and results to manage sports sponsorship with precision.',
    'login.operationLabel': 'of commercial operation',
    'login.liveLabel': 'of compliance and evidence',

    // Password Reset
    'passwordReset.title': 'Recover password',
    'passwordReset.description': 'Enter your email or username to receive a recovery code valid for 30 minutes.',
    'passwordReset.emailLabel': 'Email or username',
    'passwordReset.emailPlaceholder': 'user@example.com or your_username',
    'passwordReset.getCode': 'Get code',
    'passwordReset.sending': 'Sending...',
    'passwordReset.cancel': 'Cancel',
    'passwordReset.codeReceived': 'Code received:',
    'passwordReset.newPasswordLabel': 'New password',
    'passwordReset.newPasswordPlaceholder': 'Minimum 8 characters',
    'passwordReset.confirmPasswordLabel': 'Confirm password',
    'passwordReset.confirmPasswordPlaceholder': 'Repeat your new password',
    'passwordReset.resetButton': 'Reset password',
    'passwordReset.resetting': 'Resetting...',
    'passwordReset.back': 'Back',
    'passwordReset.successTitle': 'Password updated',
    'passwordReset.successMessage': 'Your password has been reset successfully. You will be redirected to login shortly.',
    'passwordReset.successMessage2': 'Recovery code generated. Use it in the next 30 minutes.',

    // Account Settings
    'accountSettings.title': 'Account Settings',
    'accountSettings.accountInfo': 'Account Information',
    'accountSettings.username': 'Username',
    'accountSettings.email': 'Email',
    'accountSettings.subscriptionType': 'Subscription Type',
    'accountSettings.changePassword': 'Change Password',
    'accountSettings.currentPassword': 'Current password',
    'accountSettings.newPassword': 'New password',
    'accountSettings.confirmPassword': 'Confirm new password',
    'accountSettings.passwordUpdated': 'Password updated',
    'accountSettings.passwordChanged': 'Your password has been changed successfully.',

    // Date fields for users admin
    'users.validFrom': 'Valid from',
    'users.validUntil': 'Valid until',
    'users.createdAt': 'Created at',
    'users.updatedAt': 'Updated at',
    'users.lastLoginAt': 'Last login at',

    // Form Fields - Activos
    'activo.nombreDelActivo': 'Asset name',
    'activo.categoria': 'Category',
    'activo.canalUbicacion': 'Channel or location',
    'activo.descripcion': 'Description',
    'activo.valoracionCOP': 'Valuation (COP)',
    'activo.inventarioTotal': 'Total inventory',
    'activo.inventarioDisponible': 'Available inventory',
    'activo.alcanceEstimado': 'Estimated reach',
    'activo.estado': 'Status',
    'activo.derechosIncluidos': 'Included rights',
    'activo.audienciaCapacidad': 'Audience and activation capacity',
    'activo.segmentosRelacionados': 'Related segments',
    'activo.canalActivacion': 'Activation channel',
    'activo.tipoAudiencia': 'Audience type',
    'activo.capacidadSegmentacion': 'Segmentation capacity',
    'activo.indicadoresDisponibles': 'Available indicators',
    'activo.frecuenciaMaxima': 'Maximum frequency',
    'activo.requiereSportsActGO': 'Requires Sports Act GO',
    'activo.restricciones': 'Restrictions',

    // Form Fields - Oportunidades
    'oportunidad.marca': 'Brand',
    'oportunidad.responsable': 'Responsible',
    'oportunidad.etapa': 'Stage',
    'oportunidad.valorEstimadoCOP': 'Estimated value (COP)',
    'oportunidad.probabilidad': 'Probability (%)',
    'oportunidad.fechaCierre': 'Estimated closure date',
    'oportunidad.activosPropuestos': 'Proposed assets',
    'oportunidad.proximoPaso': 'Next step',

    // Form Fields - Evidencias
    'evidencia.compromisoRelacionado': 'Related commitment',
    'evidencia.tipoEvidencia': 'Evidence type',
    'evidencia.fechaEjecucion': 'Execution date',
    'evidencia.titulo': 'Title',
    'evidencia.descripcion': 'Description',
    'evidencia.ubicacionCanal': 'Location or channel',
    'evidencia.enlace': 'Link (optional)',

    // Form Fields - Compañías
    'compania.nombre': 'Name',
    'compania.sector': 'Sector',
    'compania.nombreContacto': 'Contact name',
    'compania.telefonoContacto': 'Contact phone',
    'compania.telefono2Contacto': 'Contact phone 2',
    'compania.correoContacto': 'Contact email',
    'compania.correo2Contacto': 'Contact email 2',
    'compania.logo': 'Logo (URL or path)',

    // Form Fields - Usuarios
    'usuario.correo': 'Email',
    'usuario.usuario': 'Username',
    'usuario.contraseña': 'Password',
    'usuario.nuevaContraseña': 'New password (optional)',
    'usuario.suscripcion': 'Subscription',
    'usuario.compania': 'Company',

    // Button Actions
    'button.cancelar': 'Cancel',
    'button.guardarCambios': 'Save changes',
    'button.crearActivo': 'Create asset',
    'button.crearOportunidad': 'Create opportunity',
    'button.registrarEvidencia': 'Register evidence',
    'button.crearCompania': 'Create company',
    'button.crearSector': 'Create sector',
    'button.crearUsuario': 'Create user',
    'button.nuevoPlan': 'New plan',
    'button.guardarPlan': 'Save plan',
    'button.eliminarPlan': 'Delete plan',
    'button.cambiarContraseña': 'Change password',
    'button.atras': 'Back',
    'button.cambiando': 'Changing...',
    'button.guardando': 'Saving...',
    'button.enviando': 'Sending...',
    'button.nuevo': 'New',
    'button.editar': 'Edit',
    'button.eliminar': 'Delete',
    'button.cerrar': 'Close',

    // Page Headers & Descriptions
    'dashboard.operacion': 'Executive view of commercial operations and sponsorship compliance.',
    'activos.catalogo': 'Catalog of commercial assets available for sponsorship.',
    'acuerdos.patrocinios': 'Closed sponsorships, validity and compliance status.',
    'compromisos.entregas': 'Operational management of deliverables promised to each sponsor.',
    'evidencias.repositorio': 'Repository of proof of compliance for each commitment.',
    'oportunidades.pipeline': 'Commercial pipeline of negotiations with sponsor brands.',
    'audiencias.header': 'Audiences and Reach',
    'audiencias.descripcion': 'Management of segments, channels and reach campaigns',
    'audiencias.demoDatos': 'Demo data',
    'compania.header': 'Companies',
    'compania.descripcion': 'Register, modify and delete sponsor companies.',
    'sector.header': 'Sectors',
    'sector.descripcion': 'Configure the catalog used to classify companies.',
    'usuario.header': 'User Management',
    'usuario.descripcion': 'Create, modify and delete users, subscriptions and assigned companies.',
    'suscripcion.header': 'Subscriptions',
    'suscripcion.descripcion': 'Configure available plans, prices, limits and features.',
    'reporte.header': 'Reports',
    'reporte.descripcion': 'Executive reports of results for each sponsor.',

    // Dashboard
    'dashboard.accesosRapidos': 'Quick access',

    // Dashboard Stats
    'dashboard.valorPipeline': 'Pipeline value',
    'dashboard.oportunidadesAbiertas': 'Open opportunities',
    'dashboard.ingresosCerrados': 'Closed revenue',
    'dashboard.acuerdosActivos': 'Active agreements, about to expire and completed',
    'dashboard.activosDisponibles': 'Available assets',
    'dashboard.listosNegociar': 'Ready to negotiate',
    'dashboard.incluyeProximosVencer': 'Includes upcoming expiration',
    'dashboard.cumplimientoGeneral': 'Overall compliance',
    'dashboard.compromisoCumplidos': 'Commitments completed out of total',
    'dashboard.compromisosVencidos': 'Overdue commitments',
    'dashboard.requierenAtencion': 'Require immediate attention',
    'dashboard.totalActivos': 'Total assets',
    'dashboard.disponibles': 'Available',
    'dashboard.comprometidos': 'Committed',
    'dashboard.valorVigente': 'Current value',
    'dashboard.acuerdosTotales': 'Total agreements',
    'dashboard.proximosVencer': 'About to expire',
    'dashboard.totalCompromisos': 'Total commitments',
    'dashboard.pendientesEnCurso': 'Pending and in progress',
    'dashboard.vencidos': 'Overdue',
    'dashboard.cumplidos': 'Completed',
    'dashboard.totalEvidencias': 'Total evidence',
    'dashboard.aprobadas': 'Approved',
    'dashboard.enRevision': 'Under review',
    'dashboard.rechazadas': 'Rejected',
    'dashboard.oportunidadesAbiertas2': 'Open opportunities',
    'dashboard.valorPipeline2': 'Pipeline value',
    'dashboard.ganadas': 'Signed',

    // Filter Labels
    'filter.todosLosEstados': 'All statuses',
    'filter.todasLasPrioridades': 'All priorities',
    'filter.todosLosResponsables': 'All responsible',
    'filter.todasLasCategorias': 'All categories',
    'filter.todosLosAcuerdos': 'All agreements',
    'filter.todoLosTipos': 'All types',
    'filter.todosLosSegmentos': 'All segments',
    'filter.quitar': 'Remove filter',

    // Search Placeholders
    'search.entregable': 'Search deliverable...',
    'search.nombreCanal': 'Search by name or channel...',
    'search.acuerdoMarca': 'Search by agreement or brand...',
    'search.evidencia': 'Search evidence...',
    'search.marca': 'Search by brand...',
    'search.campana': 'Search campaign...',
    'search.marcaAcuerdo': 'Search by brand or agreement...',

    // Status Labels
    'status.borrador': 'Draft',
    'status.proximoVencer': 'About to expire',
    'status.finalizado': 'Completed',
    'status.enCurso2': 'In progress',
    'status.enRevision2': 'Under review',
    'status.aprobada': 'Approved',
    'status.rechazada': 'Rejected',
    'status.ganada': 'Signed',
    'status.perdida': 'Lost',
    'status.activa': 'Active',
    'status.finalizada': 'Finished',

    // Table Headers
    'table.entregable': 'Deliverable',
    'table.marca': 'Brand',
    'table.responsable': 'Responsible',
    'table.fechaLimite': 'Due date',
    'table.prioridad': 'Priority',
    'table.progreso': 'Progress',
    'table.estado': 'Status',
    'table.activo': 'Asset',
    'table.categoria': 'Category',
    'table.valoracion': 'Valuation',
    'table.inventario': 'Inventory',
    'table.acuerdo': 'Agreement',
    'table.valor': 'Value',
    'table.vigencia': 'Validity',
    'table.cumplimiento': 'Completion',
    'table.etapa': 'Stage',
    'table.estimado': 'Estimated value',
    'table.probabilidad': 'Probability',
    'table.cierreEstimado': 'Estimated closure',
    'table.campana': 'Campaign',
    'table.patrocinador': 'Sponsor',
    'table.canal': 'Channel',
    'table.periodo': 'Period',
    'table.alcance': 'Reach',
    'table.interacciones': 'Interactions',
    'table.conversiones': 'Conversions',
    'table.tasaConv': 'Conv. rate',
    'table.acciones': 'Actions',

    // Empty States
    'empty.noCompromisos': 'No commitments match',
    'empty.ajustaFiltros': 'Adjust your search or applied filters.',
    'empty.noActivos': 'No assets found',
    'empty.ajustaActivos': 'Adjust search filters or create a new commercial asset.',
    'empty.noAcuerdos': 'No agreements match',
    'empty.noEvidencias': 'No evidence found',
    'empty.ajustaEvidencias': 'Adjust filters or register new compliance evidence.',
    'empty.noOportunidades': 'No opportunities match',
    'empty.ajustaOportunidades': 'Adjust filters or create a new commercial opportunity.',
    'empty.noCampanas': 'No campaigns match',
    'empty.ajustaCampanas': 'Adjust filters to view other audience campaigns.',
    'empty.noReportes': 'No reports match',
    'empty.ajustaReportes': 'Search to find a sponsor report.',
    'empty.reporteNoEncontrado': 'Report not found',
    'empty.reporteNoGenerado': 'No executive report has been generated for this agreement yet.',
    'empty.acuerdoNoEncontrado': 'Agreement not found',
    'empty.acuerdoEliminado': 'It may have been deleted or the link is incorrect.',
    'empty.sinEvidencias': 'No evidence has been registered for this agreement yet.',
    'empty.sinOportunidades': 'No opportunities in this stage',
    'empty.sinActivosAsociados': 'This agreement has no associated assets.',
    'empty.sinCompromisos': 'This agreement does not yet have defined commitments.',
    'empty.sinActivosVinculados': 'No commercial assets linked yet.',
    'empty.sinCompanias': 'No companies registered yet.',
    'empty.sinDescripcion': 'No description',

    // Confirmation & Messages
    'confirm.eliminarCompania': 'Delete company {nombre}?',
    'confirm.eliminarSector': 'Delete sector {nombre}?',
    'confirm.eliminarSuscripcion': 'Delete subscription {name}?',
    'confirm.eliminarUsuario': 'Delete user {username}?',

    // Success Messages
    'message.compañiaActualizada': 'Company updated successfully.',
    'message.compañiaCreada': 'Company created successfully.',
    'message.compañiaEliminada': 'Company deleted successfully.',
    'message.sectorActualizado': 'Sector updated successfully.',
    'message.sectorCreado': 'Sector created successfully.',
    'message.sectorEliminado': 'Sector deleted successfully.',
    'message.usuarioActualizado': 'User updated successfully.',
    'message.usuarioCreado': 'User created successfully.',
    'message.usuarioEliminado': 'User deleted successfully.',
    'message.planGuardado': 'Plan saved successfully.',
    'message.planEliminado': 'Plan deleted successfully.',
    'message.activoCreado': 'Asset created successfully.',
    'message.oportunidadMovida': 'Opportunity moved to "{etapa}".',
    'message.oportunidadCreada': 'Opportunity created in the pipeline.',
    'message.evidenciaRegistrada': 'Evidence registered and sent for review.',
    'message.evidenciaAprobada': 'Evidence approved.',
    'message.evidenciaRechazada': 'Evidence rejected.',
    'message.compromisoActualizado': 'Commitment updated to "{nuevoEstado}".',
    'message.renovacionRegistrada': 'Renewal follow-up registered for this agreement.',
    'message.segmentoActualizado': 'Segment aggregate information updated.',
    'message.activoYaVinculado': 'That asset is already linked to this segment.',
    'message.datosActualizados': 'Data updated (simulation). No real connection to Sports Act GO yet.',
    'message.exportDemoAvailable': 'PDF export will be available when the backend is connected. This is a demo view.',

    // Error Messages
    'error.noGuardarCompania': 'Could not save the company.',
    'error.noEliminarCompania': 'Could not delete the company.',
    'error.noCargarCompanias': 'Could not load companies.',
    'error.noCargarSectores': 'Could not load sectors.',
    'error.noGuardarSector': 'Could not save the sector.',
    'error.noEliminarSector': 'Could not delete the sector.',
    'error.noCrearSector': 'Could not create the sector.',
    'error.noCargarUsuarios': 'Could not load users.',
    'error.noGuardarUsuario': 'Could not save the user.',
    'error.noEliminarUsuario': 'Could not delete the user.',
    'error.noEliminarPropio': 'You cannot delete the user you are logged in with.',
    'error.noCargarPlanes': 'Could not load plans.',
    'error.noGuardarPlan': 'Could not save the plan.',
    'error.noEliminarPlan': 'Could not delete the plan. Verify it has no associated users or accesses.',
    'error.contrasenaNoCoincide': 'Passwords do not match.',
    'error.contrasenaPocaLongitud': 'Password must be at least 8 characters.',
    'error.noCambiarContraseña': 'Could not change password.',
    'error.noCrearCuenta': 'Could not create account.',
    'error.noIniciarSesion': 'Could not sign in.',

    // Detail Cards
    'detail.resumenAcuerdo': 'Agreement summary',
    'detail.valorAcuerdo': 'Agreement value',
    'detail.vigencia': 'Validity',
    'detail.activosIncluidos': 'Included assets',
    'detail.compromisosRelacionados': 'Related commitments',
    'detail.verTodos': 'View all',
    'detail.patrocinador': 'Sponsor',
    'detail.responsableInterno': 'Internal responsible',
    'detail.renovacion': 'Renewal',
    'detail.interes': 'Interest',
    'detail.iniciarSeguimiento': 'Start renewal follow-up',
    'detail.seguimientoEnCurso': 'Renewal follow-up in progress.',
    'detail.vence': 'Expires',
    'detail.cumplimientoLabel': 'Completion',
    'detail.alcanceLabel': 'Reach',
    'detail.interaccionesLabel': 'Interactions',
    'detail.valorMediatico': 'Media value',
    'detail.alcanceImpresiones': 'Monthly reach and impressions',
    'detail.evolucionMetricas': 'Evolution of exposure metrics',
    'detail.compromisosTitle': 'Commitments',
    'detail.cumplidos': 'Completed',
    'detail.pendientesEnCurso': 'Pending / In progress',
    'detail.galeriaEvidencias': 'Evidence gallery',

    // Quick Actions
    'action.gestionarActivos': 'Manage assets',
    'action.verDisponibilidad': 'View availability and inventory',
    'action.verPipeline': 'View pipeline',
    'action.seguimientoNegociaciones': 'Negotiation tracking',
    'action.registrarEvidencia': 'Register evidence',
    'action.subirPrueba': 'Upload compliance proof',
    'action.verReportes': 'View reports',
    'action.resultadoPatrocinador': 'Sponsor results',

    // Misc
    'misc.contatoInformacion': 'Contact information',
    'misc.detalleTransaccional': 'Transactional detail',
    'misc.auditoriaAntecedentes': 'Audit and background',
    'misc.periodoDatos': 'Demo data',
    'misc.tabsAudiencias': 'Audience tabs',
    'misc.resumen': 'Summary',
    'misc.segmentos': 'Segments',
    'misc.canales': 'Channels',
    'misc.campanasResultados': 'Campaigns and results',
    'misc.filtrandoCampanas': 'Filtering campaigns related to segment {nombre}',
    'misc.planesDisponibles': 'Available plans',
    'misc.seleccionaPlan': 'Select a plan to edit, delete it, or create a new one.',
    'misc.seleccionadas': '{features.length} selected',
    'misc.companiasRegistradas': 'Registered companies',
    'misc.companiasDisponibles': '{companias.length} available companies',
    'misc.usuariosRegistrados': 'Users',
    'misc.usuariosDisponibles': '{users.length} registered users',
    'misc.sectoresDisponibles': 'Available sectors',
    'misc.sectoresRegistrados': '{sectores.length} registered sectors',
    'misc.codigoSuscripcion': 'Code',
    'misc.nombreSuscripcion': 'Name',
    'misc.precioCOP': 'Price COP',
    'misc.maximoUsuarios': 'Maximum users',
    'misc.descripcionSuscripcion': 'Description',
    'misc.caracteristicas': 'Features',
    'misc.sinLimite': 'Unlimited',
    'misc.seleccionaCaracteristicas': 'Select the features',
    'misc.verReporteEjecutivo': 'View executive report',
    'misc.volverReportes': 'Back to Reports',
    'misc.volverAcuerdos': 'Back to Agreements',
    'misc.periodoInforme': 'Report period:',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app-language') as Language | null;
    if (saved) return saved;
    return 'es';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app-language', lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage debe usarse dentro de LanguageProvider');
  }
  return context;
}
