import { useEffect, useState } from 'react';
import { ArrowLeft, Edit2, Plus, Trash2 } from 'lucide-react';
import { Link, Navigate } from 'react-router-dom';
import { PageHeader } from '@/components/shared/PageHeader';
import { Button } from '@/components/ui/Button';
import { Card, CardContent, CardHeader } from '@/components/ui/Card';
import { TextField } from '@/components/ui/Field';
import { Modal } from '@/components/ui/Modal';
import { getSessionUser } from '@/lib/auth';
import { loadConfiguration, request, type Compania, type Configuration } from '../lib/config';

const emptyForm = { nombre: '', sector: '', nombreContacto: '', telefonoContacto: '', telefono2Contacto: '', mailContacto: '', mail2Contacto: '', logoUrl: '' };

export function CompaniasPage() {
  const isAdmin = getSessionUser()?.subscriptionType === 'ADMIN';
  const [companias, setCompanias] = useState<Compania[]>([]);
  const [sectores, setSectores] = useState<Configuration['sectores']>([]);
  const [form, setForm] = useState(emptyForm);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');
  const [sectorModalOpen, setSectorModalOpen] = useState(false);
  const [sectorNombre, setSectorNombre] = useState('');
  const [sectorDescripcion, setSectorDescripcion] = useState('');

  useEffect(() => { loadConfiguration().then((data) => { setCompanias(data.companias); setSectores(data.sectores.filter((sector) => sector.isActive)); }).catch((value) => setError(value instanceof Error ? value.message : 'No fue posible cargar las compañías.')); }, []);
  if (!isAdmin) return <Navigate to="/" replace />;

  function editCompany(company: Compania) { setEditingId(company.id); setForm({ nombre: company.nombre, sector: company.sector, nombreContacto: company.contactName, telefonoContacto: company.phone, telefono2Contacto: company.phone2 ?? '', mailContacto: company.email, mail2Contacto: company.email2 ?? '', logoUrl: company.logoUrl ?? '' }); setMessage(''); }
  function resetForm() { setEditingId(null); setForm(emptyForm); }
  async function saveCompany(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(''); try { const path = editingId ? `/api/admin/companias/${editingId}` : '/api/admin/companias'; const data = await request<Configuration>(path, { method: editingId ? 'PATCH' : 'POST', body: JSON.stringify(form) }); setCompanias(data.companias); resetForm(); setMessage(editingId ? 'Compañía actualizada correctamente.' : 'Compañía creada correctamente.'); } catch (value) { setError(value instanceof Error ? value.message : 'No fue posible guardar la compañía.'); } finally { setSaving(false); } }
  async function deleteCompany(company: Compania) { if (!window.confirm(`¿Eliminar la compañía ${company.nombre}?`)) return; setSaving(true); try { const data = await request<Configuration>(`/api/admin/companias/${company.id}`, { method: 'DELETE' }); setCompanias(data.companias); if (editingId === company.id) resetForm(); setMessage('Compañía eliminada correctamente.'); } catch (value) { setError(value instanceof Error ? value.message : 'No fue posible eliminar la compañía.'); } finally { setSaving(false); } }
  async function createSector(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); try { const data = await request<Configuration>('/api/admin/sectores', { method: 'POST', body: JSON.stringify({ nombre: sectorNombre, descripcion: sectorDescripcion }) }); setSectores(data.sectores.filter((sector) => sector.isActive)); setForm({ ...form, sector: sectorNombre }); setSectorNombre(''); setSectorDescripcion(''); setSectorModalOpen(false); } catch (value) { setError(value instanceof Error ? value.message : 'No fue posible crear el sector.'); } finally { setSaving(false); } }

  return <div className="space-y-6"><PageHeader titulo="Compañías" descripcion="Registra, modifica y elimina compañías patrocinadoras." breadcrumbs={[{ label: 'Parametrización', to: '/parametrizacion' }, { label: 'Compañías' }]} accion={<Link to="/parametrizacion" className="inline-flex items-center gap-2 text-sm font-medium text-brand-800 hover:underline"><ArrowLeft size={16} /> Volver</Link>} />
    {message && <div className="rounded-lg border border-success-500/30 bg-success-50 px-4 py-3 text-sm text-success-700">{message}</div>}{error && <div className="rounded-lg border border-danger-500/30 bg-danger-50 px-4 py-3 text-sm text-danger-700">{error}</div>}
    <Card><CardHeader title={editingId ? 'Editar compañía' : 'Nueva compañía'} description="Completa los datos comerciales y de contacto." /><CardContent><form onSubmit={saveCompany} className="grid gap-4 sm:grid-cols-2"><TextField label="Nombre" value={form.nombre} onChange={(event) => setForm({ ...form, nombre: event.target.value })} required /><div><div className="flex items-center justify-between"><label htmlFor="company-sector" className="text-sm font-medium text-gray-700">Sector</label><button type="button" onClick={() => setSectorModalOpen(true)} className="text-xs font-semibold text-brand-700 hover:underline">Crear sector</button></div><select id="company-sector" value={form.sector} onChange={(event) => setForm({ ...form, sector: event.target.value })} required className="mt-1.5 w-full rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm text-gray-900"><option value="">Selecciona un sector</option>{sectores.map((sector) => <option key={sector.id} value={sector.nombre}>{sector.nombre}</option>)}</select></div><TextField label="Nombre del contacto" value={form.nombreContacto} onChange={(event) => setForm({ ...form, nombreContacto: event.target.value })} required /><TextField label="Teléfono contacto" value={form.telefonoContacto} onChange={(event) => setForm({ ...form, telefonoContacto: event.target.value })} required /><TextField label="Teléfono 2 contacto" value={form.telefono2Contacto} onChange={(event) => setForm({ ...form, telefono2Contacto: event.target.value })} /><TextField label="Correo contacto" type="email" value={form.mailContacto} onChange={(event) => setForm({ ...form, mailContacto: event.target.value })} required /><TextField label="Correo 2 contacto" type="email" value={form.mail2Contacto} onChange={(event) => setForm({ ...form, mail2Contacto: event.target.value })} /><TextField label="Logo (URL o ruta)" value={form.logoUrl} onChange={(event) => setForm({ ...form, logoUrl: event.target.value })} /><div className="flex gap-2 sm:col-span-2"><Button type="submit" variante="primario" disabled={saving} icono={editingId ? <Edit2 size={15} /> : <Plus size={15} />}>{editingId ? 'Guardar cambios' : 'Crear compañía'}</Button>{editingId && <Button type="button" onClick={resetForm}>Cancelar</Button>}</div></form></CardContent></Card>
    <Card><CardHeader title="Compañías registradas" description={`${companias.length} compañías disponibles`} /><CardContent className="grid gap-2 md:grid-cols-2">{companias.length === 0 && <p className="text-sm text-gray-500">Aún no hay compañías registradas.</p>}{companias.map((company) => <div key={company.id} className="flex items-center gap-3 rounded-lg border border-gray-200 px-3 py-3"><div className="min-w-0 flex-1">{company.logoUrl ? <img src={company.logoUrl} alt="" className="mb-2 h-9 w-9 rounded-md object-cover" /> : null}<strong className="block truncate text-sm text-gray-900">{company.nombre}</strong><span className="block truncate text-xs text-gray-500">{company.sector} · {company.contactName}</span></div><div className="flex shrink-0 gap-1"><Button type="button" tamano="sm" onClick={() => editCompany(company)} icono={<Edit2 size={14} />}>Editar</Button><Button type="button" tamano="sm" variante="peligro" onClick={() => deleteCompany(company)} icono={<Trash2 size={14} />}>Eliminar</Button></div></div>)}</CardContent></Card>
    <Modal abierto={sectorModalOpen} onCerrar={() => setSectorModalOpen(false)} titulo="Crear sector" descripcion="Agrega una opción para el selector de compañías." ancho="md"><form onSubmit={createSector} className="space-y-4"><TextField label="Nombre" value={sectorNombre} onChange={(event) => setSectorNombre(event.target.value)} required /><TextField label="Descripción" value={sectorDescripcion} onChange={(event) => setSectorDescripcion(event.target.value)} /><div className="flex justify-end gap-2"><Button type="button" onClick={() => setSectorModalOpen(false)}>Cancelar</Button><Button type="submit" variante="primario" disabled={saving} icono={<Plus size={15} />}>Crear sector</Button></div></form></Modal>
  </div>;
}
